package smart

// Code generated by cmd/smart-distill; DO NOT EDIT.
const DistilledExpertVersion = "expert-v9-1"

var distilledExpertCoefficients = [8][ExpertFeatureDimension]float64{
	{0.04000000, 0.31220000, 0.17000000, 0.21480000, 0.16760000, 0.06900000, 0.02640000},
	{0.04000000, 0.31697431, 0.17318744, 0.22125595, 0.16795433, 0.05523311, 0.02539486},
	{0.04000000, 0.29610000, 0.18990000, 0.26500000, 0.15000000, 0.03400000, 0.02500000},
	{0.04000000, 0.29582143, 0.19319643, 0.27258929, 0.14834821, 0.02549107, 0.02455357},
	{0.04000000, 0.27500000, 0.12420000, 0.13640000, 0.15280000, 0.23800000, 0.03360000},
	{0.04000000, 0.29459459, 0.13039501, 0.14453222, 0.16035343, 0.19916840, 0.03095634},
	{0.04000000, 0.24400000, 0.11150000, 0.11800000, 0.14100000, 0.30750000, 0.03800000},
	{0.04000000, 0.26361644, 0.11687671, 0.12421918, 0.14898630, 0.27082192, 0.03547945},
}

var distilledExpertCalibration = [8]float64{
	1.00000000, 1.00000000, 1.00000000, 1.00000000, 1.00000000, 1.00000000, 1.00000000, 1.00000000,
}

var distilledExpertManifest = DistilledArtifactManifest{
	Version:          DistilledExpertVersion,
	Source:           "analytic",
	TrainingSamples:  0,
	HoldoutSamples:   0,
	MAE:              0,
	RMSE:             0,
	P95AbsoluteError: 0,
	MeanRelative:     0,
	RankingAgreement: 1,
	Fingerprint:      "analytic-expert-v9-1",
}
