package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/metacubex/mihomo/component/smart"
)

func parseFloat(row []string, index map[string]int, key string) float64 {
	i, ok := index[key]
	if !ok || i < 0 || i >= len(row) {
		return 0
	}
	v, _ := strconv.ParseFloat(row[i], 64)
	return v
}

func parseInt(row []string, index map[string]int, key string) int64 {
	i, ok := index[key]
	if !ok || i < 0 || i >= len(row) {
		return 0
	}
	v, _ := strconv.ParseInt(row[i], 10, 64)
	return v
}

func loadSamples(path string) ([]smart.DistillProductionSample, error) {
	if path == "" {
		return nil, nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	header, err := r.Read()
	if err != nil {
		return nil, err
	}
	index := make(map[string]int, len(header))
	for i, h := range header {
		index[h] = i
	}

	var out []smart.DistillProductionSample
	for {
		row, err := r.Read()
		if err != nil {
			if err.Error() == "EOF" {
				break
			}
			return nil, err
		}
		input := smart.ModelInput{
			Success:                   parseInt(row, index, "success"),
			Failure:                   parseInt(row, index, "failure"),
			ConnectTime:               parseInt(row, index, "connect_time"),
			Latency:                   parseInt(row, index, "latency"),
			UploadTotal:               parseFloat(row, index, "upload_mb"),
			HistoryUploadTotal:        parseFloat(row, index, "history_upload_mb"),
			MaxuploadRate:             parseFloat(row, index, "maxuploadrate_kb"),
			HistoryMaxUploadRate:      parseFloat(row, index, "history_maxuploadrate_kb"),
			DownloadTotal:             parseFloat(row, index, "download_mb"),
			HistoryDownloadTotal:      parseFloat(row, index, "history_download_mb"),
			MaxdownloadRate:           parseFloat(row, index, "maxdownloadrate_kb"),
			HistoryMaxDownloadRate:    parseFloat(row, index, "history_maxdownloadrate_kb"),
			ConnectionDuration:        parseFloat(row, index, "duration_minutes"),
			HistoryConnectionDuration: parseFloat(row, index, "history_duration_minutes"),
			LossRate:                  parseFloat(row, index, "loss_rate"),
			CumulLossRate:             parseFloat(row, index, "cumul_loss_rate"),
		}
		input.IsUDP = parseFloat(row, index, "is_udp") >= 0.5
		input.IsTCP = parseFloat(row, index, "is_tcp") >= 0.5
		weight := parseFloat(row, index, "weight")
		out = append(out, smart.DistillProductionSample{Input: input, ActualWeight: weight})
	}
	return out, nil
}

func render(calibration [8]float64) string {
	coeff := smart.CompileExpertDistillation()
	var b strings.Builder
	b.WriteString("package smart\n\n")
	b.WriteString("// Code generated by cmd/smart-distill; DO NOT EDIT.\n")
	b.WriteString("const DistilledExpertVersion = \"expert-v8-1\"\n\n")
	b.WriteString("var distilledExpertCoefficients = [8][ExpertFeatureDimension]float64{\n")
	for _, row := range coeff {
		b.WriteString("\t{")
		for i, value := range row {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%.8f", value)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("var distilledExpertCalibration = [8]float64{\n\t")
	for i, value := range calibration {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%.8f", value)
	}
	b.WriteString(",\n}\n")
	return b.String()
}

func main() {
	input := flag.String("input", "", "optional smart_weight_data.csv used only for aggregate calibration")
	output := flag.String("output", "component/smart/distilled_expert_model_gen.go", "generated Go artifact")
	verify := flag.Bool("verify", false, "verify the committed artifact is reproducible")
	flag.Parse()

	samples, err := loadSamples(*input)
	if err != nil {
		panic(err)
	}
	calibration := smart.FitProductionDistillationCalibration(samples)
	content := render(calibration)

	if *verify {
		existing, err := os.ReadFile(*output)
		if err != nil {
			panic(err)
		}
		if string(existing) != content {
			fmt.Fprintln(os.Stderr, "distilled expert artifact is stale; run: go run ./cmd/smart-distill")
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*output, []byte(content), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s from %d production samples\n", *output, len(samples))
}
