package main

import (
	"encoding/csv"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"github.com/metacubex/mihomo/component/smart"
)

func parseFloat(row []string, index map[string]int, key string) float64 {
	i, ok := index[key]
	if !ok || i < 0 || i >= len(row) {
		return 0
	}
	v, _ := strconv.ParseFloat(row[i], 64)
	return v
}

func parseInt(row []string, index map[string]int, key string) int64 {
	i, ok := index[key]
	if !ok || i < 0 || i >= len(row) {
		return 0
	}
	v, _ := strconv.ParseInt(row[i], 10, 64)
	return v
}

func loadSamples(path string) ([]smart.DistillProductionSample, error) {
	if path == "" {
		return nil, nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	header, err := r.Read()
	if err != nil {
		return nil, err
	}
	index := make(map[string]int, len(header))
	for i, h := range header {
		index[h] = i
	}

	var out []smart.DistillProductionSample
	for {
		row, err := r.Read()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return nil, err
		}
		input := smart.ModelInput{
			Success:                   parseInt(row, index, "success"),
			Failure:                   parseInt(row, index, "failure"),
			ConnectTime:               parseInt(row, index, "connect_time"),
			Latency:                   parseInt(row, index, "latency"),
			UploadTotal:               parseFloat(row, index, "upload_mb"),
			HistoryUploadTotal:        parseFloat(row, index, "history_upload_mb"),
			MaxuploadRate:             parseFloat(row, index, "maxuploadrate_kb"),
			HistoryMaxUploadRate:      parseFloat(row, index, "history_maxuploadrate_kb"),
			DownloadTotal:             parseFloat(row, index, "download_mb"),
			HistoryDownloadTotal:      parseFloat(row, index, "history_download_mb"),
			MaxdownloadRate:           parseFloat(row, index, "maxdownloadrate_kb"),
			HistoryMaxDownloadRate:    parseFloat(row, index, "history_maxdownloadrate_kb"),
			ConnectionDuration:        parseFloat(row, index, "duration_minutes"),
			HistoryConnectionDuration: parseFloat(row, index, "history_duration_minutes"),
			LossRate:                  parseFloat(row, index, "loss_rate"),
			CumulLossRate:             parseFloat(row, index, "cumul_loss_rate"),
		}
		input.IsUDP = parseFloat(row, index, "is_udp") >= 0.5
		input.IsTCP = parseFloat(row, index, "is_tcp") >= 0.5
		weight := parseFloat(row, index, "weight")
		teacherWeight := parseFloat(row, index, "teacher_weight")
		out = append(out, smart.DistillProductionSample{
			Input: input, ActualWeight: weight, TeacherWeight: teacherWeight,
		})
	}
	return out, nil
}

func render(calibration [8]float64) string {
	coeff := smart.CompileExpertDistillation()
	var b strings.Builder
	b.WriteString("package smart\n\n")
	b.WriteString("// Code generated by cmd/smart-distill; DO NOT EDIT.\n")
	b.WriteString("const DistilledExpertVersion = \"expert-v8-1\"\n\n")
	b.WriteString("var distilledExpertCoefficients = [8][ExpertFeatureDimension]float64{\n")
	for _, row := range coeff {
		b.WriteString("\t{")
		for i, value := range row {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%.8f", value)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("var distilledExpertCalibration = [8]float64{\n\t")
	for i, value := range calibration {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%.8f", value)
	}
	b.WriteString(",\n}\n")
	return b.String()
}

func main() {
	input := flag.String("input", "", "optional smart_weight_data.csv used only for aggregate calibration")
	output := flag.String("output", "component/smart/distilled_expert_model_gen.go", "generated Go artifact")
	verify := flag.Bool("verify", false, "verify the committed artifact is reproducible")
	maxLogRMSE := flag.Float64("max-log-rmse", 0.35, "reject production calibration above this log-RMSE")
	flag.Parse()

	samples, err := loadSamples(*input)
	if err != nil {
		panic(err)
	}
	calibration := smart.FitProductionDistillationCalibration(samples)
	if *verify && *input == "" {
		// Verification without the private production dataset checks that the
		// committed analytical coefficients still reproduce the source experts
		// while preserving whatever aggregate calibration is already embedded.
		calibration = smart.CurrentDistilledExpertCalibration()
	}

	report := smart.EvaluateProductionDistillation(samples, calibration)
	if len(samples) > 0 {
		fmt.Printf(
			"distill_quality samples=%d base_log_rmse=%.6f calibrated_log_rmse=%.6f max_relative_error=%.6f\n",
			report.Count, report.BaseLogRMSE, report.CalibratedLogRMSE, report.MaxRelativeError,
		)
		for i, bucket := range report.Buckets {
			if bucket.Count == 0 {
				continue
			}
			fmt.Printf(
				"bucket=%d samples=%d base_log_rmse=%.6f calibrated_log_rmse=%.6f max_relative_error=%.6f\n",
				i, bucket.Count, bucket.BaseLogRMSE, bucket.CalibratedLogRMSE, bucket.MaxRelativeError,
			)
		}
		if !smart.ProductionDistillationAcceptable(report, *maxLogRMSE) {
			fmt.Fprintln(os.Stderr, "production distillation rejected: quality gate failed")
			os.Exit(2)
		}
	}

	content := render(calibration)
	if *verify {
		existing, err := os.ReadFile(*output)
		if err != nil {
			panic(err)
		}
		if string(existing) != content {
			fmt.Fprintln(os.Stderr, "distilled expert artifact is stale; run: go run ./cmd/smart-distill")
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*output, []byte(content), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s from %d production samples\n", *output, len(samples))
}
